spring.application.name=backend

# Désactivation temporaire de la BD (pas de DB configurée pour le moment)
spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
  org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration
